INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Programming', 'Nerdy business');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('3D printing', 'Nerdy business');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Acrobatics', 'Less nerdy business');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Acting', 'Chuck Norris is an actor');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Amateur radio', 'Do they even have music?');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Animation', 'Svampebob Firkant er gruppens favorit animation');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Baking', 'Cake is great');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Beatboxing', 'Ba Dum Tss');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Programming', 'Nerdy business');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Football', 'No, I do not mean soccer!');
INSERT INTO HOBBY (NAME, DESCRIPTION) VALUES ('Gaming', 'pewpew');
